<p style="text-align: justify;">
    <span style="color:#f00;"><strong>1. ÁMBITO</strong></span><br>
    <br>
    <strong>1.1.</strong> Las presentes Condiciones Generales, junto a las Condiciones Particulares que puedan establecerse, regularán expresamente las relaciones surgidas entre spainelectro.com (), con domicilio en Madrid, calle Valdeon, 12 local 17, 28943 MADRID y con CIF nº B-86789575 (en adelante, ”spainelectro.com") y los terceros (en adelante, "Usuarios" o "Usuario") que utilicen el portal de Internet "www.spainelectro.com" y/o "www.spainelectro.com" (en adelante el "Portal"), así como con los terceros que contraten los productos y servicios ofrecidos o accesibles a través del mismo (en adelante los "Productos y Servicios").<br>
    <strong>1.2.</strong> Las presentes Condiciones Generales no excluyen la posibilidad de que la adquisición y/o utilización de alguno de los Productos y/o Servicios ofrecidos a los Usuarios a través del Portal que se encuentre sometida a condiciones específicas de uso ("Condiciones Particulares"), que complementarán a estas Condiciones Generales y prevalecerán sobre ellas en caso de discrepancias. Los Productos y/o Servicios cuya adquisición y/o prestación fuera objeto de Condiciones Particulares se regirán por lo dispuesto en tales Condiciones Particulares y asimismo, en todo aquello no contemplado en las mismas, por lo establecido en estas Condiciones Generales.<br>
    <strong>1.3.</strong> Mediante la realización de una compra o pedido, o la contratación de un servicio, independientemente de la forma en que este se realice, el usuario reconoce y expresamente acepta estas condiciones generales de contratación, las cuáles regirán durante la vigencia de las relaciones comerciales entre comprador y vendedor sin necesidad de ulterior referencia.<br>
    <strong>1.4.</strong> spainelectro.com podrá en cualquier momento y sin previo aviso, modificar las presentes Condiciones Generales o, en su caso, las Condiciones Particulares e introducir nuevas condiciones de uso, incluido en su caso el carácter remunerado o gratuito de cualquiera de los Productos y/o Servicios del Portal. Dichas modificaciones serán publicadas en el sitio web correspondiente al Portal de forma que el Usuario pueda conocerlas antes de proceder a su utilización. La utilización del Portal y/o la adquisición de cualquiera de los Productos y/o Servicios del mismo por el Usuario una vez modificadas las Condiciones Generales o, en su caso, las Condiciones Particulares que fueran de aplicación, significará la aceptación de dicho Usuario de las Condiciones Generales o Particulares así modificadas.<br>
	<span style="color:#f00;"><strong><br>
            2. ACCESO A LOS PRODUCTOS Y SERVICIOS.</strong></span><br>
    <br>
    <strong>2.1.</strong> Para la utilización de algunos de los Productos y/o Servicios, spainelectro.com solicitará a los Usuarios que se registren. Los datos obtenidos por este procedimiento quedarán sometiditos a la "Política de Privacidad" accesible a través del Portal. El procedimiento de registro será el que en cada momento aparezca en la correspondiente sección del Portal.<br>
    <strong>2.2.</strong> La contraseña elegida por el Usuario y validada, en su caso por spainelectro.com para los Usuarios que se registren, se considerará un elemento identificador y habilitador para acceder, adquirir y utilizar los Productos y/o Servicios correspondientes y tendrá carácter personal e intransferible. El Usuario se obliga a guardar la debida diligencia en la conservación de la contraseña que le sea validada por spainelectro.com, asumiendo en caso contrario, las consecuencias que pudieran derivarse del uso de la misma por terceras personas distintas del Usuario. El Usuario no deberá escribir la contraseña de forma inteligible o accesible para un tercero, ni anotarla en un lugar accesible a terceros. spainelectro.com podrá efectuar, con un adecuado preaviso, modificaciones en la contraseña. En este caso, las contraseñas sustituidas perderán su validez.<br>
    <strong>2.3</strong>. spainelectro.com se reserva el derecho a decidir, en cada momento, los Productos y Servicios que se contengan, se ofrezcan, se presten o se hagan accesibles a los Usuarios a través del Portal. En particular, spainelectro.com podrá en cualquier momento adicionar nuevos Productos y Servicios a los incluidos en el Portal, entendiéndose que salvo que se disponga otra cosa, tales nuevos Productos y Servicios se regirán por lo dispuesto en las Condiciones Generales en vigor en ese momento. Asimismo, spainelectro.com se reserva el derecho a dejar de prestar o facilitar el acceso y utilización en cualquier momento y sin previo aviso de cualquiera de los Productos y Servicios que integran el Portal.<br>
    <strong>2.4.</strong> spainelectro.com se reserva, además, el derecho a modificar unilateralmente en cualquier momento y sin aviso previo, la presentación y configuración del Portal.<br>
    <br>
    <span style="color:#f00;"><strong>3. OBLIGACIONES DEL USUARIO</strong></span><br>
    <br>
    <strong>3.1.</strong> El Usuario se obliga, con carácter general, a utilizar el Portal y cada uno de los Productos y Servicios de forma diligente, de conformidad con la ley, la moral, el orden público y lo dispuesto en estas Condiciones Generales y en las Particulares que sean de aplicación, y deberá asimismo abstenerse de utilizarlos en cualquier forma que pueda impedir, dañar o deteriorar el normal funcionamiento y disfrute del Portal y de todos los Productos y Servicios por parte de los Usuarios o que pudiera lesionar o causar daños a los bienes y derechos de spainelectro.com, sus proveedores, Usuarios o en general de cualquier tercero.<br>
    <strong>3.2.</strong> Más en particular, pero sin que esta enumeración limite el alcance general de la obligación dispuesta en el párrafo anterior, el Usuario se obliga en la utilización del Portal y de todos y cada uno de los Servicios, así como en la adquisición de los Productos y Servicios:<br>
    <strong>(a)</strong> En caso de registrarse, deberá proporcionar verazmente los datos solicitado y mantenerlos actualizados.<br>
    <strong>(b)</strong> No introducir, almacenar o difundir cualquier información o material que fuera difamatorio, injurioso, obsceno, amenazador, xenófobo, incite a la violencia, que incite a la discriminación por razones de sexo, raza, ideología o religión o que de cualquier forma atente contra la moral, el orden público, los derechos fundamentales, las libertades públicas, el honor, la intimidad o la imagen de terceros y en general la normativa vigente.<br>
    <strong>(c)</strong> No introducir, almacenar o difundir mediante el Portal o a través de cualquiera de los Servicios, y a no utilizar en relación con los mismos, ningún programa de ordenador, dato, virus, código, equipo de hardware o de telecomunicaciones o cualquier otro instrumento o dispositivo electrónico o físico que sea susceptible de causar daños en el Portal, en cualquiera de los Servicios, o en cualesquiera equipos, sistemas o redes de spainelectro.com, de cualquier Usuario, de sus proveedores o en general de cualquier tercero, o que de otra forma sea capaz de causarles cualquier tipo de alteración o impedir el normal funcionamiento de los mismos.<br>
    <strong>(d)</strong> No realizar, salvo en aquellos espacios en que expresamente se dediquen a tales fines, actividades publicitarias, promocionales o de explotación comercial.<br>
    <strong>(e)</strong> No utilizar identidades falsas ni suplantar la identidad de otros en la utilización del Portal o en la utilización o adquisición de cualquiera de los Productos y/o Servicios, incluyendo la utilización en su caso de contraseñas o claves de acceso de terceros o de cualquier otra forma.<br>
    <strong>(f)</strong> No ocultar ni falsear en manera alguna el origen de mensajes de correo electrónico, no interceptar, borrar ni modificar los mensajes de correo electrónico de otros Usuarios, ni enviar mensajes de correo masivo.<br>
    <strong>(g) </strong>No destruir, alterar, inutilizar o dañar los datos, informaciones, programas o documentos electrónicos de spainelectro.com, sus proveedores o terceros.<br>
    <strong>(h)</strong> No introducir, almacenar o difundir mediante el Portal o a través de cualquiera de los Productos y/o Servicios cualquier contenido que infrinja derechos de propiedad intelectual, industrial o secretos empresariales de terceros, ni en general ningún contenido respecto del cual no ostentara, de conformidad con la ley, el derecho a ponerlo a disposición de terceros.<br>
    <strong>(i)</strong> No utilizar los contenidos y en particular la información obtenida a través del Portal o de cualquiera de los Productos y/o Servicios para remitir publicidad, enviar mensajes con fines de venta directa o con cualquier otro fin comercial, ni para recoger o almacenar datos personales de terceros.<br>
	<span style="color:#f00;"><strong><br>
            4. VENTA DE PRODUCTOS Y PRESTACIÓN DE SERVICIOS</strong></span><br>
    <br>
    <strong>4.1.</strong> Las características de los Productos y/o Servicios, y sus precios aparecen en pantalla. Los Productos y/o Servicios estarán disponibles para su venta hasta fin de existencias. Los precios indicados en pantalla son en euros y son los vigentes. Las ofertas están debidamente marcadas e identificadas como tal. Su plazo de validez tiene efectividad mientras aparezcan en pantalla o durante el plazo que se indiquen en la misma. No obstante lo anterior, spainelectro.com enviará factura a todas las personas físicas o jurídicas residentes en España. La confirmación de pedido enviada por spainelectro.com no tiene validez como factura, solo como comprobante de compra.<br>
    <strong>4.2.</strong> Las características y descripciones de los productos son facilitadas por sus respectivos fabricantes, por lo que spainelectro.com no puede garantizar la exactitud, calidad, veracidad, fiabilidad que ofrece esta información.<br>
    <strong>4.3.</strong> En caso de no hallarse disponible el bien objeto del pedido, el vendedor podrá suministrar sin aumento de precio un producto de características similares que tenga la misma o superior calidad. En caso de no estar conforme con la entrega el usuario podrá solicitar el abono de las cantidades abonadas, dirigiéndose para ello al servicio de atención al usuario<br>
    <strong>4.4.</strong> En cuanto a los servicios sobre un dispositivo, spainelectro.com examinará el artículo nada más recibirlo. En caso de detectar alguna anomalía o avería adicional a lo descrito por el cliente se lo hará saber, pudiendo presupuestarle a parte dicha reparación. Los precios aplicables a cada reparación están expuestos en el Portal, así como las condiciones particulares de cada servicio. Igualmente, una vez efectuada una reparación y comunicada su disponibilidad al Usuario para recoger el artículo, se establece el plazo de 30 días naturales para que sea retirado. A partir de ese plazo, se cobrará dos euros por cada día adicional que el producto esté en las dependencias de spainelectro.com, en concepto de almacenaje.<br>
    <strong>4.5.</strong> El usuario se obliga a salvaguardar los datos que conserve en el hardware que quiera reparar, mediante copia de seguridad, para evitar la pérdida de datos que pueda producirse derivada de la reparación. Respecto al software, se excluye la responsabilidad por defectos causados por el Usuario con motivo de actualizaciones, instalaciones incorrectas o de software adicional o periféricos. En tal caso el Usuario correrá con dichos gastos, aun cuando tales defectos surjan en la reparación de un Hardware en garantía.<br>
    <strong>4.6.</strong> Si, en el curso de una reparación, surgieren defectos no previstos y no presupuestados, spainelectro.com informará al usuario de tal extremo, y de ser necesario, elaborará un presupuesto adicional.<br>
    <strong>4.7.</strong> Todo el contenido (ya sea digital o físico) existente en un dispositivo así como sus accesorios que sean entregados a spainelectro.com, pertenecen a su propietario, siendo éste el único responsable a todos los efectos sobre dicho contenido.<br>
    <br>
    &nbsp;<br>
    <span style="color:#f00;"><strong>5. PRECIOS Y CONDICIONES DE PAGO</strong></span><br>
    <strong><br>
        5.1.</strong> La lista de precios vigente en el momento de la aceptación del pedido o de la compraventa es vinculante. Precios exclusivos para la página web. Podrían variar en tienda física.<br>
    <strong>5.2.</strong> El plazo de pago de las facturas se entiende vencido por el hecho de la entrega de los bienes, sin perjuicio de las entregas a domicilio.<br>
    <strong>5.3.</strong> Las formas de pago disponibles para el portal son: Pago al contado, transferencia o ingreso bancario, tarjeta de crédito / débito, Paypal, Contrarrembolso. Las formas de pago vigentes en cualquier caso, serán las establecidas en el apartado “formas de pago" disponible en el Portal.<br>
    <strong>5.4.</strong> spainelectro.com se reserva el derecho de eliminar, añadir o modificar unilateralmente en cualquier momento y sin aviso previo, las formas de pago disponibles, así como sus condiciones o gastos adicionales que puedan acarrear.<br>
    <strong>5.5. </strong>Algunas formas de pago pueden estar restringidas a determinadas zonas geográficas o a algunos productos o servicios en concreto.<br>
    <strong>5.6.</strong> La forma de pago "Contrarrembolso" supone un contrato vinculante entre el Usuario y spainelectro.com. Por lo que una vez realizado un pedido y habiendo seleccionado este método de pago, el usuario se compromete al pago de dicho pedido. En caso contrario, deberá abonar a spainelectro.com los gastos derivados de dicha transacción, que corresponderán a los costes de envíos de dicho producto, más seis euros en concepto de gastos de gestión y pago del envío de vuelta a origen<br>
    <strong>5.7.</strong> spainelectro.com se reserva el derecho de retener temporalmente un pedido o un pago recibido si se observan detalles que puedan indicar un intento de fraude o para realizar todas las comprobaciones oportunas que garanticen la veracidad del pago.<br>
	<span style="color:#f00;"><strong><br>
            6. ENVÍO Y CONDICIONES DE ENTREGA</strong></span><br>
    <br>
    <strong>6.1. </strong>spainelectro.com realiza envíos nacionales e internacionales y lo hace a través de terceros transportistas contratados al efecto.<br>
    <strong>6.2.</strong> La entrega se efectuará en el domicilio o dirección indicada por el usuario. En caso de equivocación al indicar la dirección o de querer cambiarla posteriormente, el Usuario deberá hacerse cargo de los cargos derivados que resulten como consecuencia de esta modificación.<br>
    <strong>6.3.</strong> El plazo de entrega del pedido depende de la disponibilidad de los artículos solicitados. En el caso de comprar varios artículos con distinta disponibilidad, el envío se realizará una vez estén todos los artículos disponibles, es decir, habrá que tener en cuenta el artículo cuyo plazo de entrega sea mayor.<br>
    <strong>6.4. </strong>Todos los productos permanecerán en propiedad de spainelectro.com hasta que no se vea satisfecho el pago total del importe de los mismos.<br>
    <strong>6.5.</strong> Algunos métodos de envío pueden estar disponibles exclusivamente para algunas zonas geográficas.<br>
    <strong>6.6.</strong> Las tarifas de envío, así como las modalidades de envío disponibles, serán las establecidas en el apartado “Formas de envio" del portal.<br>
    <strong>6.7.</strong> spainelectro.com se reserva el derecho de añadir, eliminar o modificar las modalidades de envío disponibles, así como sus tarifas sin previo aviso. En cualquier caso en el momento de formalizar el pedido y antes de efectuar el pago definitivo, se le informará de las tarifas exactas para ese pedido.<br>
    <strong>6.8.</strong> El Usuario al realizar un pedido se compromete a recibirlo en la dirección indicada y a revisar toda la mercancía en el momento de su recepción. En caso de venir dañado el paquete o que se observen síntomas de manipulación, deberá hacerlo constar en el albarán de entrega del mensajero y comunicar la incidencia ante spainelectro.com y la compañía de transportes en un plazo inferior a 24h. desde la recepción del pedido.<br>
    &nbsp;<br>
    <span style="color:#f00;"><strong>7. DEVOLUCIONES</strong></span><br>
    <br>
    <strong>7.1.</strong> DEVOLUCIONES PARA CLIENTES PARTICULARES<br>
    <strong>7.1.1.</strong>&nbsp; Derecho al desistimiento. Tal y como establece la LEY 47/2002, de 19 de diciembre, de reforma de la Ley 7/1996, de 15 de enero, de Ordenación del Comercio Minorista, para la transposición al ordenamiento jurídico español de la Directiva 97/7/CE, en materia de contratos a distancia, y para la adaptación de la Ley a diversas Directivas comunitarias el Usuario tiene derecho a la devolución del pedido durante los siete días hábiles siguientes a la recepción del pedido, sin necesidad de justificar la decisión y sin penalización de ninguna clase (siempre que el uso no vaya más allá de la mera comprobación del buen estado y funcionamiento del producto). El cliente deberá asumir los gastos derivados del envío para la devolución del bien.<br>
    <strong>7.1.2.</strong> Para solicitarlo, deberá rellenar el "Documento de Devolución por Desistimiento", disponible en la sección de Devoluciones y que se adjunta con cada pedido y comunicar de forma escrita (ya sea por mail, carta o fax) su deseo de acogerse a tal derecho en el plazo máximo de siete días hábiles desde la recepción del pedido. Una vez aceptada la devolución por el departamento Postventa, se asignará un número de devolución y el cliente dispodrá de otros 7 días hábiles para hacer llegar por su cuenta y cargo el material a las dependencias de spainelectro.com.&nbsp; En el apartado "Devoluciones" de la página web se encuentran todos la información y documentos sobre el proceso de devolución.<br>
    <strong>7.1.3.</strong>Tal y como especifica dicha ley, el derecho de desistimiento previsto en la citada norma no resultará de aplicación a la grabaciones sonoras o de vídeo, de discos, de programas informáticos y/o videojuegos que hubiesen sido desprecintados por el consumidor, así como de ficheros informáticos, suministrados por vía electrónica, susceptibles de ser descargados o reproducidos con carácter inmediato para su uso permanente, ni a los Productos que puedan ser reproducidos o copiados con carácter inmediato, (compact disc, software, películas de vídeo, libros, videojuegos, etcétera). Tampoco resultará de aplicación los productos o dispositivos que hayan sido fabricados, configurados o montados a medida y a petición del cliente, así como cualquier modificación, reparación o trabajo realizado en algún artículo solicitado por el cliente.<br>
    <strong>7.1.4.</strong> spainelectro.com procederá al abono siempre y cuando proceda, en el plazo máximo de 30 días a partir de la recepción de la mercancía a devolver, pese a que intentará realizarlo lo antes posible.<br>
    <strong>7.1.5.</strong> Además, y sin perjuicio del derecho de desistimiento que contempla la ley para la devolución de un producto en los siete días hábiles posteriores a la fecha de recepción del pedido, spainelectro.com amplía este plazo a 15 días hábiles, para aquellos casos en los que el producto no haya sido usado y se encuentre en perfecto estado su embalaje, sin haber sido abierto o desprecintado.<br>
    <strong>7.1.6.</strong> En caso de detectarse alguna anomalía en el producto o embalaje provocada por mal uso o manipulación indebida, o no cumplir las condiciones de devolución expuestas (en plazo o forma de presentación), spainelectro.com podrá rechazar la devolución, y enviará el material de nuevo al cliente, quién deberá hacerse cargo de los portes de envío de vuelta (en función del producto que sea) más 6€ en concepto de gastos de gestión y administración.<br>
    <br>
    &nbsp;<br>
    <strong>7.2.</strong> <span style="color:#f00;"><strong>CONDICIONES DE DEVOLUCIONES PARA EMPRESAS Y PROFESIONALES</strong></span><br>
    <strong><br>
        7.2.1.</strong> Únicamente se aceptarán devoluciones de material sin desprecintar y en perfecto estado, durante los 7 días hábiles posteriores a su recepción.<br>
    <strong>7.2.2. </strong>Tales devoluciones serán tramitadas como devolución comercial, y para poder solicitarlas habrá que seguir los pasos indicados en el apartado "Devoluciones" del Portal, ya que no hay ninguna ley que regule los derechos de devolución entre empresas y dichas tramitaciones están reguladas según las condiciones de&nbsp; spainelectro.com. En tal caso, deberá notificarse la intención de devolver un producto en los siete días hábiles siguientes a la recepción del pedido. Una vez aprobada la devolución, el material deberá llegar a las instalaciones de&nbsp; spainelectro.com en un plazo no superior a siete días desde la aceptación de dicha devolución, corriendo por cuenta y cargo del cliente el envío (salvo que el motivo de la devolución sea por defecto de fábrica)<br>
    <strong>&nbsp;7.2.3</strong> Productos en blíster o termo sellado, y resto de productos que presenten un precinto de fábrica de seguridad roto, no será posible devolverse; como por ejemplo, placas base con cables desprecintados, monitores, impresoras, tarjetas de memoria, componentes, repuestos, recambios, software, videojuegos, equipos montados o configurados a medida, moviles modificados o personalizadas, etc.<br>
    <strong>7.2.4. </strong>En caso de detectarse alguna anomalía en el producto o embalaje provocada por mal uso o manipulación indebida, o no cumplir las condiciones de devolución expuestas (en plazo o forma de presentación), spainelectro.com podrá rechazar la devolución, y enviará el material de nuevo al cliente, quién deberá hacerse cargo de los portes de envío de vuelta (en función del producto que sea) más 6€ en concepto de gastos de gestión y administración.<br>
    <br>
    &nbsp;<br>
    <span style="color:#f00;"><strong>8. GARANTÍA</strong></span><br>
    <br>
    <strong>8.1.&nbsp;</strong> spainelectro.com garantiza según las leyes vigentes y las siguientes condiciones todos los artículos, componentes y demás productos que distribuye. Únicamente prestará el servicio de garantía sobre bienes que hayan sido adquiridos en su establecimiento. En función del producto la garantía deberá ser tramitada directamente con el fabricante del mismo.&nbsp; spainelectro.com se ofrecerá siempre como intermediario en caso de que el Usuario así lo desee.<br>
    <strong>8.2. </strong>La garantía para todos los artículos nuevos de la página web será de dos años a contar a partir de la fecha de entrega del producto, período que podría ser mayor en función del producto, en cuyo caso quedará especificado en su ficha y en la factura de compra.<br>
    <strong>8.3.</strong> Los artículos de segunda mano, considerando como tal aquellos que han sido usados previamente por otro propietario, así como aquellos que pese a ser nuevos deben ser abiertos y modificados para ampliar sus funcionalidades o características, tendrá como mínimo un año de garantía.<br>
    <strong>8.4</strong>. Cuando el artículo adquirido presente una falta de conformidad porque no se corresponda con las características ofrecidas, presente defectos que impidan su normal utilización con arreglo a su naturaleza o no ofrezca las prestaciones descritas para él, el Usuario tiene derecho al saneamiento del bien adquirido en un plazo de dos años a partir de la compra, en las condiciones y con los medios de prueba regulados en el Texto Refundido de la Ley General para la Defensa de Consumidores y Usuarios y sin perjuicio de las facultades de&nbsp; spainelectro.com para comprobar la veracidad de los defectos, su origen y momento de aparición.<br>
    <strong>8.5.</strong> La reparación que se encuentre en garantía tendrá carácter gratuito, y spainelectro.com procederá, según corresponda, a la reparación, sustitución, rebaja del precio o resolución del contrato. El Usuario deberá notificar al vendedor de la falta de conformidad en el plazo de dos meses desde que tuvo conocimiento de ella,&nbsp; siguiendo las indicaciones del apartado "garantia" del Portal. Siempre que el producto esté en garantía los gastos de envío correrán por cuenta y cargo de&nbsp; spainelectro.com.<br>
    <strong>8.6.</strong> spainelectro.com informará al cliente del plazo que conllevará la tramitación de la garantía, intentando siempre que sea el mínimo posible y estableciéndose un máximo de tres meses desde la recepción del artículo. La garantía de la reparación efectuada en productos en garantía comercial, tendrá una duración de seis meses. Si son probados que los defectos invocados por el Usuario no fueran ciertos o por cualquier otra causa no sean objeto de la Garantía,&nbsp; spainelectro.com podrá presupuestar la reparación fuera de garantía, pudiendo requerir al Usuario el importe derivado de los gatos de envío, administración y gestión de la garantía. En la misma forma se procederá cuando los defectos invocados deriven de un uso inadecuado del artículo, cuando el producto hubiere sido manipulado por terceros antes de la reclamación, mala conservación, fuerza mayor, o por cualquier otra causa ajena al artículo o a&nbsp; spainelectro.com. A estos efectos se considerará que existe en todo caso uso inadecuado o mala conservación cuando no se haya dado cumplimiento a las instrucciones contenidas en el manual o documentación entregada junto con el artículo.<br>
    <strong>8.7. </strong>Con carácter general, el Usuario se compromete a inspeccionar de inmediato el artículo adquirido y a comunicar lo antes posible a&nbsp; spainelectro.com cualquier posible disconformidad con el mismo, evitando en todo caso el agravamiento de cualquier daño, bajo un principio de buena fe.<br>
    <strong>8.8.&nbsp; </strong>spainelectro.com podrá disponer a disposición del Usuario una póliza de seguro que extienda los períodos de garantía comercial por encima de los ofrecidos en cada caso por el comprador del artículo. Este seguro, cuando exista, será de suscripción voluntaria por el Usuario, y su coste será exclusivamente por cuenta del Usuario. Tanto las tarifas como condiciones contractuales de la póliza estarán a disposición del comprador.<br>
    <strong>8.9.</strong> Para las empresas y profesionales, la garantía será la que establezca directamente el fabricante del artículo en cuestión, así como el procedimiento para gestionarlas, ya que no hay ninguna ley que especifique el procedimiento de Garantía entre profesionales.<br>
    <strong>8.10.</strong> Todos los detalles sobre la tramitación de garantía, plazos, procedimiento, etc... están expuestos en la sección "Garantia" del Portal.<br>
    <strong>8.11.&nbsp;</strong> Por último, los servicios tales como reparaciones, modificaciones, servicio técnico, etc...efectuados en productos que se encuentren fuera del periodo de garantía comercial, quedarán garantizados por tres meses tal y como establece la ley. Dicho plazo entra en vigor a partir de la fecha de entrega del aparato. La garantía es total sobre la reparación efectuada e incluye transporte, piezas e impuestos, siempre y cuando la nueva avería sea la misma que ha sido reparada. Queda fuera del ámbito de esta garantía cualquier avería distinta a la que fue reparada o piezas que no hayan sido sustituidas con motivo de la anterior reparación.<br>
    <br>
	<span style="color:#f00;"><strong>&nbsp;<br>
            9. PROPIEDAD INTELECTUAL E INDUSTRIAL</strong></span><br>
    <br>
    <strong>9.1 </strong>El Usuario reconoce que todos los elementos del Portal y de cada uno de los Productos y Servicios, la información y materiales contenidos en los mismos, las marcas, la estructura, selección, ordenación y presentación de sus contenidos, y los programas de ordenador utilizados en relación con ellos, están protegidos por derechos de propiedad intelectual e industrial de la propia spainelectro.com o de terceros, y que las Condiciones Generales no le atribuyen respecto a dichos derechos de propiedad industrial e intelectual ningún otro derecho distinto de los específicamente contemplados en las mismas.<br>
    <strong>9.2 </strong>Salvo que fuera autorizado por spainelectro.com o en su caso por los terceros titulares de los derechos correspondientes, o a menos que ello resulte legalmente permitido, el Usuario no podrá reproducir, transformar, modificar, desensamblar, realizar ingeniería inversa, distribuir, alquilar, prestar, poner a disposición, o permitir el acceso al público a través de cualquier modalidad de comunicación pública de ninguno de los elementos referidos en el párrafo anterior. El Usuario deberá utilizar los materiales, elementos e información a la que acceda a través de la utilización del Portal y de cada uno de los Productos y Servicios únicamente para sus propias necesidades, obligándose a no realizar ni directa ni indirectamente una explotación comercial ni de los Productos y Servicios ni de los materiales, elementos e información obtenidos a través de los mismos.<br>
    <strong>9.3 </strong>El Usuario deberá abstenerse de suprimir los signos identificativos de los derechos (de propiedad intelectual, industrial o cualquier otro) de&nbsp; spainelectro.com o de los terceros que figuren en el Portal, así como abstenerse de eludir o manipular cualesquiera dispositivos técnicos establecidos por&nbsp; spainelectro.com o por terceros en el Portal<br>
    <br>
    &nbsp;<br>
    <span style="color:#f00;"><strong>10. RESPONSABILIDAD</strong></span><br>
    <br>
    <strong>10.1.</strong> Sin perjuicio de la responsabilidad por daños y perjuicios que se pudiera derivar,&nbsp; spainelectro.com podrá, con carácter inmediato y sin necesidad de preaviso, resolver y dar por terminada su relación con el Usuario, o interrumpir su acceso al Portal y/o el acceso y utilización de cualquiera de los Productos y/o Servicios, si detecta un uso del Portal o de cualquiera de los Productos y/o Servicios contrario a las presentes Condiciones Generales o a las Condiciones Particulares que sean de aplicación.<br>
    <strong>10.2.</strong> El Usuario responderá de los daños y perjuicios de toda naturaleza que&nbsp; spainelectro.com pueda sufrir directa o indirectamente, como consecuencia del incumplimiento de cualquiera de las obligaciones derivadas de las Condiciones Generales o Particulares en relación con la utilización del Portal o de cualquiera de los Productos y/o Servicios. Asimismo, el Usuario mantendrá a&nbsp; spainelectro.com indemne frente a cualquier sanción, reclamación o demanda que pudiera interponerse por un tercero, incluidos cualesquiera organismos públicos, contra&nbsp; spainelectro.com, sus empleados o agentes como consecuencia de la violación de cualesquiera derechos de terceros por parte de dicho Usuario mediante la utilización del Portal o de cualquiera de los Productos y/o Servicios o, en general, que pudiera interponerse como consecuencia de la utilización o adquisición de cualquiera de los Productos y/o Servicios en una forma contraria a lo previsto en las Condiciones Generales o en las Condiciones Particulares que fueran de aplicación.<br>
    <strong>10.3.</strong> El Usuario reconoce y acepta que la utilización del Portal, así como la adquisición y utilización de los Productos y/o Servicios se realiza a su entero riesgo, bajo su única y exclusiva responsabilidad.<br>
    <strong>10.4.</strong>&nbsp; spainelectro.com no otorga ninguna garantía, y excluye cualquier responsabilidad por los daños y perjuicios que pudieran derivarse, respecto a los extremos siguientes:<br>
    <strong>(a) </strong>Disponibilidad, continuidad y utilidad:&nbsp; spainelectro.com se compromete a llevar a cabo todos los esfuerzos necesarios para posibilitar la disponibilidad y continuidad del Portal. Sin embargo,&nbsp; spainelectro.com no puede garantizar que el Portal funcione correctamente en todo momento, que el Usuario podrá acceder a él y utilizarlo de forma rápida, ininterrumpida y libre de errores, ni que todos los errores serán corregidos. De la misma forma,&nbsp; spainelectro.com no otorga ninguna garantía respecto a la idoneidad del Portal o de cualquiera de los Productos y/o Servicios para la satisfacción de necesidades específicas de un Usuario;<br>
    <strong>(b)</strong> Seguridad:&nbsp; spainelectro.com adoptará las medidas de seguridad generalmente adoptadas en el sector para garantizar la confidencialidad y seguridad de la utilización del Portal. No obstante,&nbsp; spainelectro.com no puede garantizar que terceros no autorizados puedan tener conocimiento de las características y circunstancias del uso que los Usuarios realizan del Portal y de los Productos y/o Servicios.<br>
    <strong>(c)</strong>&nbsp; spainelectro.com actuará diligentemente según los usos generalmente aceptados en el sector para evitar la presencia en el Portal de virus u otros elementos lesivos que pudieran causar alteraciones en el sistema informático del Usuario, en sus documentos electrónicos o en sus ficheros, pero no puede garantizar la ausencia de tales elementos, no siendo responsable por los daños y perjuicios que ello pudiera ocasionar.<br>
    <strong>(d)</strong> Servicios prestados por terceros:&nbsp; spainelectro.com no controla, ni hace propios, ni garantiza la exactitud, calidad, veracidad, fiabilidad o idoneidad de las informaciones, productos y servicios facilitados o prestados por terceros a través del Portal. De igual forma no controla y no garantiza la ausencia de virus u otros elementos lesivos en los contenidos o servicios facilitados o prestados por terceros a través del Portal.<br>
    <strong>(e)</strong> Contenidos fuera del Portal:&nbsp; spainelectro.com no garantiza la disponibilidad técnica, calidad, fiabilidad, exactitud o veracidad de los contenidos, productos y servicios disponibles en sitios pertenecientes o gestionados por terceros a los que el Usuario pueda acceder mediante dispositivos técnicos de enlace ("links") desde el Portal.&nbsp; spainelectro.com no controla el contenido de dichos sitios web ni ofrece ni comercializa los productos y servicios disponibles en los sitios web así enlazados, ni asume en consecuencia responsabilidad alguna por los mismos.<br>
    <strong>(f)&nbsp;</strong> spainelectro.com no otorga garantías de naturaleza alguna, ni expresa ni implícitamente, respecto de la utilización que los Usuarios hagan del Portal, ni del incumplimiento de las obligaciones legales a la que estén obligados los Usuarios.<br>
    &nbsp;<span style="color:#f00;"><strong><br>
            11. COMUNICACIONES y ATENCIÓN AL CLIENTE</strong></span><br>
    <br>
    <strong>11.1.</strong> Salvo que otra cosa se prevea expresamente en estas Condiciones Generales,&nbsp; spainelectro.com puede enviar al Usuario comunicaciones mediante carta, a la dirección que consta en la ficha de registro, o por correo electrónico, a la dirección de correo electrónico que figure registrada en dicha ficha. El Usuario expresamente autoriza el envío de comunicaciones a través de correo electrónico.<br>
    <strong>11.2.</strong> Asimismo, y salvo que otra cosa se disponga expresamente en estas Condiciones Generales, el Usuario puede comunicarse con&nbsp; spainelectro.com para gestionar cualquier incidencia con el uso del Portal o contratación de productos o servicios, mediante envío de carta postal o email, mediante las líneas telefónicas de atención al usuario o usando el formulario de contacto disponible en el Portal.<br>
    <strong>11.3.</strong> En caso de cambio de domicilio de cualquiera de las partes, deberá comunicarlo a la otra parte por cualquiera de los medios antes indicados.<br>
    <br>
    <span style="color:#f00;"><strong>12. PROTECCIÓN DE DATOS</strong></span><br>
    <br>
    <strong>12.1.</strong> El Usuario queda informado y consiente en que los datos facilitados a través de los formularios de solicitud de datos, así como los que se generen como consecuencia de su relación establecidas con nosotros se incorporarán a un fichero automatizado titularidad de Game Service Soluciones Tecnicas S.L. (spainelectro.com), inscrito en la Agencia Española de Protección de Datos Personales, con la finalidad de gestionar, administrar y prestarle los servicios que solicite, gestionar el registro de usuarios, gestionar las compras que se efectúen, así como informarle de productos o servicios, propios o de tercero que puedan resultar de su interés.<br>
    spainelectro.com declara y garantiza la completa sumisión y cumplimiento efectivo de los procesos de garantía y seguridad contenidos en la Ley de Protección de Datos LO 15/1.999 del 13 de diciembre de Regulación del Tratamiento Automatizado de Datos de Carácter Personal.<br>
    <strong>12.2.</strong> Todos los datos, en cumplimiento con la LOPD, quedarán sometidos a la "política de privacidad" accesible a través del Portal.<br>
    <strong>12.3.</strong> Conforme a la Ley de Protección de Datos, Ley Orgánica 15/1.999 del 13 de diciembre, el Usuario tendrá la posibilidad de ejercer los derechos de acceso, rectificación, cancelación y oposición de sus datos personales que obran en los ficheros de spainelectro.com, solicitándolo por cualquier medio que deje constancia de su envío y de su recepción.&nbsp; Para ejercer sus derechos podrá dirigirse por escrito a través de cualquier de estos dos medios:<br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#f00;"> Correo Postal:</span><br>
    <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; spainelectro.com <br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; At:&nbsp; LOPD - Protección de Datos<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; c/ Valdeon, 12 (Local 17) -&nbsp; 28039 Madrid</strong><br>
    <br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="color:#f00;">Correo Electrónico:</span><br>
    <strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Asunto del email: LOPD - Protección de Datos<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; info@spainelectro.com</strong><br>
	<span style="color:#f00;"><strong><br>
            13. DURACION Y TERMINACION</strong></span><br>
    <br>
    <strong>13.1. </strong>La prestación del servicio de Portal tiene, en principio, una duración indefinida, spainelectro.com, no obstante, está autorizada para dar por terminada o suspender la prestación del servicio del Portal en cualquier momento, sin perjuicio de lo que se hubiere dispuesto al respecto en las correspondientes Condiciones Particulares. Cuando ello sea razonablemente previsible, spainelectro.com advertirá acerca de la terminación o suspensión de la prestación del servicio de Portal.<br>
    <br>
    <span style="color:#f00;"><strong>14. LEY APLICABLE Y ASOCIACIONES</strong></span><br>
    <br>
    <strong>14.1. </strong>Las disposiciones contenidas en estas Condiciones Generales se regirán y serán interpretadas de conformidad con la legislación española, que será aplicable en relación a su validez, interpretación, ejecución y cumplimiento. Las partes se someten, a su elección, para la resolución de los conflictos y renuncia a cualquier otro fuero, a los juzgados y tribunales de Madrid.</p>